"""add comments table

Revision ID: 5282c913551a
Revises: 82d531d559f2
Create Date: 2026-04-01 15:46:59.005168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5282c913551a'
down_revision: Union[str, Sequence[str], None] = '82d531d559f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.Text(), nullable=False))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###
