"""empty message

Revision ID: 6138a9260e26
Revises: 
Create Date: 2026-04-01 09:53:51.764109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6138a9260e26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_bookings', 'status',
               existing_type=postgresql.ENUM('scheduled', 'completed', 'cancelled', 'no_show', name='booking_status'),
               type_=sa.Enum('scheduled', 'completed', 'cancelled', 'no_show', name='bookingstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'scheduled'::booking_status"))
    op.create_index(op.f('ix_class_bookings_id'), 'class_bookings', ['id'], unique=False)
    op.alter_column('course_schedules', 'day_of_week',
               existing_type=postgresql.ENUM('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', name='day_of_week'),
               type_=sa.Enum('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', name='dayofweek'),
               existing_nullable=True)
    op.create_index(op.f('ix_course_schedules_id'), 'course_schedules', ['id'], unique=False)
    op.alter_column('courses', 'level',
               existing_type=postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'Business', name='course_level'),
               type_=sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'Business', name='courselevel'),
               existing_nullable=True)
    op.alter_column('courses', 'type',
               existing_type=postgresql.ENUM('individual', 'group', name='course_type'),
               type_=sa.Enum('individual', 'group', name='coursetype'),
               existing_nullable=True)
    op.alter_column('courses', 'regime',
               existing_type=postgresql.ENUM('remote', 'in-person', 'hybrid', name='course_regime'),
               type_=sa.Enum('remote', 'in_person', 'hybrid', name='courseregime'),
               existing_nullable=True)
    op.alter_column('courses', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'full', 'completed', name='course_status'),
               type_=sa.Enum('draft', 'active', 'full', 'completed', name='coursestatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::course_status"))
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.alter_column('enrollments', 'status',
               existing_type=postgresql.ENUM('active', 'completed', 'transferred', 'canceled', name='enrollment_status'),
               type_=sa.Enum('active', 'completed', 'transferred', 'canceled', name='enrollmentstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::enrollment_status"))
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_hour_packages_id'), 'hour_packages', ['id'], unique=False)
    op.create_index(op.f('ix_hour_transfers_id'), 'hour_transfers', ['id'], unique=False)
    op.alter_column('notifications', 'channel',
               existing_type=postgresql.ENUM('whatsapp', 'email', name='notification_channel'),
               type_=sa.Enum('whatsapp', 'email', name='notificationchannel'),
               existing_nullable=True)
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('pending', 'sent', 'failed', name='notification_status'),
               type_=sa.Enum('pending', 'sent', 'failed', name='notificationstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::notification_status"))
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='payment_status'),
               type_=sa.Enum('pending', 'paid', 'failed', 'refunded', name='paymentstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::payment_status"))
    op.alter_column('payments', 'type',
               existing_type=postgresql.ENUM('package', 'extra_hour', 'trial', name='payment_type'),
               type_=sa.Enum('package', 'extra_hour', 'trial', name='paymenttype'),
               existing_nullable=True)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.alter_column('pre_enrollments', 'status',
               existing_type=postgresql.ENUM('pending', 'converted', 'cancelled', name='pre_enrollment_status'),
               type_=sa.Enum('pending', 'converted', 'cancelled', name='preenrollmentstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::pre_enrollment_status"))
    op.create_index(op.f('ix_pre_enrollments_id'), 'pre_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_availability_id'), 'teacher_availability', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('student', 'admin', name='user_role'),
               type_=sa.Enum('student', 'admin', name='userrole'),
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('waitlist', 'status',
               existing_type=postgresql.ENUM('waiting', 'offered', 'accepted', 'expired', name='waitlist_status'),
               type_=sa.Enum('waiting', 'offered', 'accepted', 'expired', name='waitliststatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'waiting'::waitlist_status"))
    op.create_index(op.f('ix_waitlist_id'), 'waitlist', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_id'), table_name='waitlist')
    op.alter_column('waitlist', 'status',
               existing_type=sa.Enum('waiting', 'offered', 'accepted', 'expired', name='waitliststatus'),
               type_=postgresql.ENUM('waiting', 'offered', 'accepted', 'expired', name='waitlist_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'waiting'::waitlist_status"))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('student', 'admin', name='userrole'),
               type_=postgresql.ENUM('student', 'admin', name='user_role'),
               existing_nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_index(op.f('ix_teacher_availability_id'), table_name='teacher_availability')
    op.drop_index(op.f('ix_pre_enrollments_id'), table_name='pre_enrollments')
    op.alter_column('pre_enrollments', 'status',
               existing_type=sa.Enum('pending', 'converted', 'cancelled', name='preenrollmentstatus'),
               type_=postgresql.ENUM('pending', 'converted', 'cancelled', name='pre_enrollment_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::pre_enrollment_status"))
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.alter_column('payments', 'type',
               existing_type=sa.Enum('package', 'extra_hour', 'trial', name='paymenttype'),
               type_=postgresql.ENUM('package', 'extra_hour', 'trial', name='payment_type'),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('pending', 'paid', 'failed', 'refunded', name='paymentstatus'),
               type_=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='payment_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::payment_status"))
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'status',
               existing_type=sa.Enum('pending', 'sent', 'failed', name='notificationstatus'),
               type_=postgresql.ENUM('pending', 'sent', 'failed', name='notification_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::notification_status"))
    op.alter_column('notifications', 'channel',
               existing_type=sa.Enum('whatsapp', 'email', name='notificationchannel'),
               type_=postgresql.ENUM('whatsapp', 'email', name='notification_channel'),
               existing_nullable=True)
    op.drop_index(op.f('ix_hour_transfers_id'), table_name='hour_transfers')
    op.drop_index(op.f('ix_hour_packages_id'), table_name='hour_packages')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.alter_column('enrollments', 'status',
               existing_type=sa.Enum('active', 'completed', 'transferred', 'canceled', name='enrollmentstatus'),
               type_=postgresql.ENUM('active', 'completed', 'transferred', 'canceled', name='enrollment_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::enrollment_status"))
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.alter_column('courses', 'status',
               existing_type=sa.Enum('draft', 'active', 'full', 'completed', name='coursestatus'),
               type_=postgresql.ENUM('draft', 'active', 'full', 'completed', name='course_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::course_status"))
    op.alter_column('courses', 'regime',
               existing_type=sa.Enum('remote', 'in_person', 'hybrid', name='courseregime'),
               type_=postgresql.ENUM('remote', 'in-person', 'hybrid', name='course_regime'),
               existing_nullable=True)
    op.alter_column('courses', 'type',
               existing_type=sa.Enum('individual', 'group', name='coursetype'),
               type_=postgresql.ENUM('individual', 'group', name='course_type'),
               existing_nullable=True)
    op.alter_column('courses', 'level',
               existing_type=sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'Business', name='courselevel'),
               type_=postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'Business', name='course_level'),
               existing_nullable=True)
    op.drop_index(op.f('ix_course_schedules_id'), table_name='course_schedules')
    op.alter_column('course_schedules', 'day_of_week',
               existing_type=sa.Enum('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', name='dayofweek'),
               type_=postgresql.ENUM('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', name='day_of_week'),
               existing_nullable=True)
    op.drop_index(op.f('ix_class_bookings_id'), table_name='class_bookings')
    op.alter_column('class_bookings', 'status',
               existing_type=sa.Enum('scheduled', 'completed', 'cancelled', 'no_show', name='bookingstatus'),
               type_=postgresql.ENUM('scheduled', 'completed', 'cancelled', 'no_show', name='booking_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'scheduled'::booking_status"))
    # ### end Alembic commands ###
